# Generated by Django 5.1.4 on 2024-12-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
