# Generated by Django 5.1.4 on 2024-12-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt_app', '0002_organization__id_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='_id',
            new_name='object_id',
        ),
    ]
