# Generated by Django 5.1.4 on 2024-12-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt_app', '0004_organization_deleted_organization_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
