# Generated by Django 5.1.4 on 2024-12-27 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt_app', '0005_organization_description_organization_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Do not add sensitive information', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Your organization name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(help_text="if given 'test' url will be: https://test.host.com", max_length=12),
        ),
    ]
